name: kraken
version: 1.0.0
config-version: 2
profile: kraken
model-paths:
- models
macro-paths:
- macros
vars:
  csv_path: data/oracle_address_sample_100_au_streets.csv
  filters: {}
  required_fields: []
  column_map: {}
  transformations: {}
  active_record_filter: {}
  row_limit: 25
models:
  kraken:
    landing:
      +schema: landing
      +materialized: table
    bronze:
      +schema: bronze
      +materialized: table
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
