SELECT *
FROM {{ ref('landing_address') }}
WHERE ADDRESS_ID   IS NOT NULL
  AND PARTY_ID     IS NOT NULL
  AND ADDRESS_TYPE IS NOT NULL
  AND LENGTH(CAST(POSTCODE AS VARCHAR)) = 4
  AND (END_DATE IS NULL OR END_DATE > CURRENT_DATE)
